"""Trusted workbench composition over the shipped workspace packages."""
from contextlib import redirect_stderr, redirect_stdout
import hashlib
import io
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT / "packages" / name) for name in ("core", "create-vivary", "tropo")]
import create_vivary
import tropo
from vivary_core.creation_provider_stdio import CreationProviderComposition


class ShippedWorkspaceOperations:
    """The host owns scratch custody; create-vivary owns every generated byte."""

    def __init__(self, *, recovery_parent: Path):
        self.recovery_parent = recovery_parent.resolve(strict=True)
        if not self.recovery_parent.is_dir():
            raise ValueError("recovery preview parent must be a provisioned directory")

    @staticmethod
    def _options(options):
        return dict(preset=options.preset, adapters=options.adapters,
                    active_context=options.active_context)

    def plan(self, target, options):
        return create_vivary.plan_thin_workspace(target, **self._options(options))

    def recovery_plan(self, target, options):
        # Render beside the occupied target while preserving its project name.
        plan = create_vivary.plan_thin_workspace(self.recovery_parent / target.name, **self._options(options))
        plan["target"] = str(target)
        body = {key: value for key, value in plan.items() if key != "plan_sha256"}
        raw = json.dumps(body, sort_keys=True, separators=(",", ":")).encode()
        plan["plan_sha256"] = "sha256:" + hashlib.sha256(raw).hexdigest()
        return plan

    def scaffold(self, target, options):
        return create_vivary.scaffold_thin_workspace(target, repo_root=ROOT, **self._options(options))

    def doctor(self, target):
        return create_vivary.doctor_workspace(target, repo_root=ROOT)

    def tropo(self, target):
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            return tropo.main(["check", "--root", str(target)])


def shipped_creation_composition(*, parents, namespace, recovery_parent):
    """Build the existing stdio provider inputs from trusted startup facts."""
    return CreationProviderComposition(
        parents=parents, namespace=namespace,
        operations=ShippedWorkspaceOperations(recovery_parent=recovery_parent),
    )
